name: kolors
description: The named HTML colors that you can use in your Flutter apps.
version: 0.1.0+3
homepage: https://www.github.com/dartsidedev/kolors
repository: https://www.github.com/dartsidedev/kolors
issue_tracker: https://www.github.com/dartsidedev/kolors/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0